name: Ders Notları Bütünlük Kontrolü

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:
    # Manuel tetikleme için

jobs:
  kontrol:
    runs-on: ubuntu-latest
    steps:
      - name: Repoyu Klonla
        uses: actions/checkout@v3

      - name: Python Kur
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Bağımlılıkları Yükle
        run: |
          python -m pip install --upgrade pip
          pip install pandas tabulate colorama

      - name: Ders Notları Kontrolü
        id: kontrol
        run: |
          python .github/scripts/ders_notlari_kontrol.py
        
      - name: Sonuçları Artifacts Olarak Kaydet
        uses: actions/upload-artifact@v3
        with:
          name: ders-notlari-rapor
          path: rapor.md
          retention-days: 90
