name: Ders Notları Bütünlük Kontrolü

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:
    # Manuel tetikleme için

jobs:
  kontrol:
    runs-on: ubuntu-latest
    steps:
      - name: Repository'yi Al
        uses: actions/checkout@v4

      - name: Dosya Listesini Al 
        id: file_list
        uses: actions/github-script@v7
        with:
          script: |
            const repo = context.repo;
            const path = '';
            const { data: repoContents } = await github.rest.repos.getContent({
              owner: repo.owner,
              repo: repo.repo,
              path: path,
              ref: context.sha
            });
            
            // Recursive olarak tüm dosyaları alacak function
            async function getAllFiles(path = '') {
              const files = [];
              
              const { data: contents } = await github.rest.repos.getContent({
                owner: repo.owner,
                repo: repo.repo,
                path: path,
                ref: context.sha
              });
              
              for (const item of contents) {
                if (item.type === 'file') {
                  files.push({
                    name: item.name,
                    path: item.path
                  });
                } else if (item.type === 'dir' && !item.path.includes('.git')) {
                  const subFiles = await getAllFiles(item.path);
                  files.push(...subFiles);
                }
              }
              
              return files;
            }
            
            const allFiles = await getAllFiles();
            core.setOutput('files', JSON.stringify(allFiles));
            
            // Debug için konsola yaz
            console.log(`Toplam ${allFiles.length} dosya bulundu.`);

      - name: Python Kur
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Bağımlılıkları Yükle
        run: |
          python -m pip install --upgrade pip
          pip install pandas tabulate colorama

      - name: Python Betiğini İndir
        run: |
          mkdir -p .github/scripts
          curl -o .github/scripts/ders_notlari_kontrol.py https://raw.githubusercontent.com/${{ github.repository }}/master/.github/scripts/ders_notlari_kontrol.py
          chmod +x .github/scripts/ders_notlari_kontrol.py

      - name: Ders Notları Kontrolü
        id: kontrol
        run: |
          echo '${{ steps.file_list.outputs.files }}' > file_list.json
          python .github/scripts/ders_notlari_kontrol.py
        
      - name: Sonuçları Artifacts Olarak Kaydet
        uses: actions/upload-artifact@v4
        with:
          name: ders-notlari-rapor
          path: rapor.md
          retention-days: 90
